### ISSUE TITLE
Training results.

### ISSUE THREAD

**Issue by sutiankang** [jahongir7174/YOLOv8-pt#1]
Thank you for your effort!
Could you please tell me the details of your training on the COCO dataset. My own training 100 epochs only has about 25 mAP, which is far from the official performance.
Thanks!

**Comment by jahongir7174** [comment]
The repo is in the experimental phase.
You can look [MMYOLO](https://github.com/open-mmlab/mmyolo/blob/main/configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py) configuration file for training details. I could not find detailed instructions for reproducing the results in the original repo. The provided [weights](https://github.com/jahongir7174/YOLOv8-pt/releases/tag/v0.0.1-alpha) are ported from the original repository. As I know, epochs and the total batch size should be 500 and 128 for reproducing the original results

**Comment by sutiankang** [comment]
> The repo is in the experimental phase. You can look [MMYOLO](https://github.com/open-mmlab/mmyolo/blob/main/configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py) configuration file for training details. I could not find detailed instructions for reproducing the results in the original repo. The provided [weights](https://github.com/jahongir7174/YOLOv8-pt/releases/tag/v0.0.1-alpha) are ported from the original repository. As I know, epochs and the total batch size should be 500 and 128 for reproducing the original results

Thank you for your reply

**Comment by jahongir7174** [comment]
You can check the latest code to reproduce the results

**Comment by sutiankang** [comment]
> You can check the latest code to reproduce the results
Thanks
