### ISSUE TITLE
inference performance

### ISSUE THREAD

**Issue by kabdelmonem** [jahongir7174/YOLOv8-pt#2]
hello thank you for the code,
i am testing it along with the ultralytics implementation on my pc and noticed that the inference time per image when using this implemntation is a lot slower any ideas as to why?

**Comment by jahongir7174** [comment]
@kabdelmonem I checked the validation time of both `nano` versions of both repositories on the `COCO` validation set when the batch size and the number of workers are one.
It took almost the same time to validate 5K images. Please make sure all configurations are the same when you are comparing the models

**Comment by kabdelmonem** [comment]
okay thank you
