### ISSUE TITLE
CSP 不是 yolov5 里面的么

### ISSUE THREAD

**Issue by jolt2017** [jahongir7174/YOLOv8-pt#3]

**Comment by jahongir7174** [comment]
@jolt2017 CSP layers used in [YOLOv5](https://github.com/jahongir7174/YOLOv5-pt/blob/33ad8bae521025ac8e32abd2bdc6890b159c1a04/nets/nn.py#L69) and [YOLOv8](https://github.com/jahongir7174/YOLOv8-pt/blob/ed290bdc9896106ac03374939dd6947c3ed57f54/nets/nn.py#L61) are not the same. You can find the difference in the provided link.
