### ISSUE TITLE
Question: Originality and license

### ISSUE THREAD

**Issue by josht000** [jahongir7174/YOLOv8-pt#5]
First of all I see you've been very busy creating some nice opensource projects. Thanks for that. Ultralytics makes nice projects as well but they add a lot of abstraction away from the core PyTorch layers which can be frustrating to deal with. 

Question, if you were to get into a legal battle with Ultralytics could you say that your code itself is genuinely yours (ie. not copied or derived from Ultralytics)? I'm not referring to the architecture which I know you're trying tor replicate through your own ingenuity.

Thanks!

**Comment by jahongir7174** [comment]
@josht000 
I copied some parts of the code from [YOLOv5](https://github.com/ultralytics/yolov5), [YOLOv8](https://github.com/ultralytics/ultralytics), and [TIMM](https://github.com/huggingface/pytorch-image-models).
All codes in the repository do not belong to me but some parts.

**Comment by josht000** [comment]
@jahongir7174 Thanks for that. However, you'd probably have to adopt the same license as Ultralytics has and put that in your code.
