### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by josht000** [jahongir7174/YOLOv8-pt#6]
All code needs a license of some sort like [MIT](https://opensource.org/license/mit/), [Apache 2.0,](https://www.apache.org/licenses/LICENSE-2.0.txt) the [Unlicense license](https://github.com/realworldocaml/examples/blob/master/UNLICENSE) etc. Could you please chose a permissive O/S license for your project?

**Comment by jahongir7174** [comment]
@josht000 
I have added the license the same as the original [YOLOv8](https://github.com/ultralytics/ultralytics)
